baseURL = "https://justinjstark.com/"
languageCode = "en-us"
title = "Justin J Stark"

# Enable syntax highlighting.
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# Your Google analytics code.
googleAnalytics = ""

# Number of posts to show in recent posts list (Optional). Defaults to 10.
paginate = 10

# Social media links which shows up on site header.
[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/justinjstark"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/justinjstark"
